[project]
name = "whisker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncio>=4.0.0",
    "dotenv>=0.9.9",
    "ffmpeg>=1.4",
    "openai-whisper>=20250625",
    "python-telegram-bot>=22.5",
]
